logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    root: warn
    '[org.jmresler.jpa]': info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nibrs
    username: root
    password: password
    hikari:
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
