logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    root: warn
    '[org.jmresler.jpa]': debug

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/${spring.application.name}-db;mode=DB2
    username: app
    password: app
    hikari:
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    defer-datasource-initialization: true
    # generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  sql:
    init:
      mode: always

